Repository nasa-fornax/fornax-demo-notebooks, pull requests merged in 2022-10, with the labels that each got.

#62 DOC: Sort out automated fornax-api cloning & add Troy to authors
  forced_photometry/multiband_photometry.ipynb
Labels: documentation

#64 BUG: Update the fornax API usage
  forced_photometry/multiband_photometry.ipynb
Labels: bug

#65 MAINT: Several changes to iron out bugs and improve UX
  code/cutout.py
  forced_photometry/multiband_photometry.ipynb
Labels: bug, ready-for-review
