Repository nasa-fornax/fornax-demo-notebooks, pull requests merged in 2023-12, with the labels that each got.

#185 Bugfix Table to DataFrame conversion
  light_curves/code_src/WISE_functions.py
Labels: use case: light curves

#178 Break heasarc TAP calls, each call has a maximum number of sources
  light_curves/code_src/heasarc_functions.py
Labels: use case: light curves

#183 Bugfix dtypes
  light_curves/code_src/WISE_functions.py
  light_curves/code_src/ztf_functions.py
  light_curves/lc_classifier.md
Labels: use case: light curves, use case: ML

#187 ENH: HTML rendering configuration and index files
  README.md
  conf.py
  forced_photometry/README.md
  index.md
  light_curves/README.md
Labels: infrastructure

#190 CI: adding publishing GHA
  .github/workflows/ci_publish.yml
  site-requirements.txt
  tox.ini
Labels: documentation, infrastructure

#192 CI: adding logo, and updating action versions
  .github/workflows/ci_publish.yml
  _static/fornax_logo.png
Labels: infrastructure

#189 Light curve text cleanup
  README.md
  light_curves/code_src/HCV_functions.py
  light_curves/code_src/README.md
  light_curves/code_src/TESS_Kepler_functions.py
  light_curves/code_src/WISE_functions.py
  light_curves/code_src/data_structures.py
  light_curves/code_src/gaia_functions.py
  light_curves/code_src/heasarc_functions.py
  light_curves/code_src/icecube_functions.py
  light_curves/code_src/mast_functions.py
  light_curves/code_src/panstarrs.py
  light_curves/code_src/ztf_functions.py
  light_curves/light_curve_generator.md
Labels: use case: light curves

#186 MAINT: update dependencies and versions
  light_curves/requirements-lc_classifier.txt
  light_curves/requirements.txt
Labels: infrastructure

#194 BUG: fix function names after rename
  light_curves/code_src/sample_lc.py
Labels: bug
