Repository nasa-fornax/fornax-demo-notebooks, pull requests merged in 2024-08, with the labels that each got.

#301 Add runtime & explanatory text to light_curve_classifier.md
  light_curves/light_curve_classifier.md
Labels: use case: ML classifier

#305 adding runtime info to intro of spectra_generator
  spectroscopy/spectra_generator.md
Labels: use case: spectroscopy

#300 MAINT: Changing progress bar to better behave with renderings
  forced_photometry/multiband_photometry.md
  forced_photometry/requirements.txt
  light_curves/code_src/ML_utils.py
  light_curves/code_src/heasarc_functions.py
  light_curves/code_src/panstarrs_functions.py
  light_curves/code_src/tess_kepler_functions.py
  light_curves/code_src/wise_functions.py
  light_curves/code_src/ztf_functions.py
  light_curves/light_curve_classifier.md
  light_curves/requirements-lc_classifier.txt
  light_curves/requirements.txt
  spectroscopy/requirements.txt
Labels: infrastructure

#315 Update multiband_photometry.md
  forced_photometry/multiband_photometry.md
Labels: use case: forced photometry, maintanence

#319 CI: update action that got moved org
  .github/workflows/circleci-artifacts-redirector.yml
Labels: infrastructure, maintanence

#318 MAINT: Uniformise how to handle dependency install cell
  forced_photometry/multiband_photometry.md
  forced_photometry/requirements.txt
  forced_photometry/requirements_multiband_photometry.txt
  light_curves/ML_AGNzoo.md
  light_curves/light_curve_classifier.md
  light_curves/light_curve_generator.md
  light_curves/requirements-lc_classifier.txt
  light_curves/requirements_ML_AGNzoo.txt
  light_curves/requirements_light_curve_classifier.txt
  light_curves/requirements_light_curve_generator.txt
  light_curves/requirements_scale_up.txt
  light_curves/scale_up.md
Labels: refactor, maintanence

#328 HTML: adding TOC structure to sidebar
  index.md
  tox.ini
Labels: infrastructure, HTML rendering

#327 DEP: remove usage of deprecated servicetype
  forced_photometry/multiband_photometry.md
Labels: maintanence
