Repository nasa-fornax/fornax-demo-notebooks, pull requests merged in 2024-03, with the labels that each got.

#238 Improve ZTF RAM usage
  light_curves/code_src/ztf_functions.py
Labels: ready-for-review, use case: light curves

#210 DOC: adding generic documentation to the HTML rendering
  conf.py
  index.md
  tox.ini
Labels: documentation

#248 CI: allowing git commands for tox
  tox.ini
Labels: infrastructure

#251 CI: adding circleCI for PRs
  .circleci/config.yml
  .github/workflows/circleci-artifacts-redirector.yml
Labels: infrastructure

#250 DOC: Adding deployed URL to main README
  README.md
Labels: documentation

#237 ML classifier cleanup
  light_curves/light_curve_classifier.md
  light_curves/light_curve_generator.md
  light_curves/requirements-lc_classifier.txt
Labels: use case: ML classifier

#259 Move functions out
  light_curves/code_src/classifier_functions.py
  light_curves/light_curve_classifier.md
Labels: use case: ML classifier
