Repository nasa-fornax/fornax-demo-notebooks, pull requests merged in 2025-09, with the labels that each got.

#495 Add Fornax contact info and standardize headings
  forced_photometry/multiband_photometry.md
  light_curves/ML_AGNzoo.md
  light_curves/light_curve_classifier.md
  light_curves/light_curve_collector.md
  light_curves/scale_up.md
  spectroscopy/spectra_collector.md
Labels: maintanence

#501 Change kernel name
  crossmatch/ztf_ps1_crossmatch.md
Labels: maintanence

#507 MAINT: small infrastructure updates to address recent CI issues
  light_curves/scale_up.md
  spectroscopy/requirements_spectra_collector.txt
  spectroscopy/spectra_collector.md
  tox.ini
Labels: infrastructure

#510 CI: make GHA job work with all its triggers
  .github/workflows/ci_publish.yml
Labels: infrastructure

#506 Fix ZTF time min/max for plotting
  light_curves/code_src/plot_functions.py
Labels: use case: light curves

#516 MAINT: Adding more data files to the manifest
  deployed_notebooks_manifest.in
Labels: infrastructure, use case: forced photometry
